joint_groups:
  group:
    joints:
      - r_arm_joint1
      - r_arm_joint2
      - r_arm_joint3
      - r_arm_joint4
      - r_arm_joint5
      - r_arm_joint6
      - r_arm_joint7
      - r_gripper_joint
    sync_read:
      - position
      - velocity
      - current
    sync_write:
      - position

r_arm_joint1: { id: 2, dynamixel: "XM540", operating_mode: 3 }
r_arm_joint2: { id: 3, dynamixel: "XM540", operating_mode: 3 }
r_arm_joint3: { id: 4, dynamixel: "XM540", operating_mode: 3 }
r_arm_joint4: { id: 5, dynamixel: "XM540", operating_mode: 3 }
r_arm_joint5: { id: 6, dynamixel: "XM430", operating_mode: 3 }
r_arm_joint6: { id: 7, dynamixel: "XM430", operating_mode: 3 }
r_arm_joint7: { id: 8, dynamixel: "XM430", operating_mode: 3 }
r_gripper_joint: { id: 9, dynamixel: "XM430", operating_mode: 3 }
