joint_groups:
  group:
    joints:
      - l_arm_joint1
      - l_arm_joint2
      - l_arm_joint3
      - l_arm_joint4
      - l_arm_joint5
      - l_arm_joint6
      - l_arm_joint7
      - l_gripper_joint
    sync_read:
      - position
      - velocity
      - current
    sync_write:
      - position

l_arm_joint1: { id: 10, dynamixel: "XM540", operating_mode: 3 }
l_arm_joint2: { id: 11, dynamixel: "XM540", operating_mode: 3 }
l_arm_joint3: { id: 12, dynamixel: "XM540", operating_mode: 3 }
l_arm_joint4: { id: 13, dynamixel: "XM540", operating_mode: 3 }
l_arm_joint5: { id: 14, dynamixel: "XM430", operating_mode: 3 }
l_arm_joint6: { id: 15, dynamixel: "XM430", operating_mode: 3 }
l_arm_joint7: { id: 16, dynamixel: "XM430", operating_mode: 3 }
l_gripper_joint: { id: 17, dynamixel: "XM430", operating_mode: 3 }
